export const metadataConfig = {
   title: "Create T3 App",
   description: "Generated by create-t3-app",
   icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export const primaryColor = "#2664eb"

export const clerkAppearence = {
   variables: {
      colorPrimary: primaryColor,
   },
}
